apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-vrurstys
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-vrurstys:2950a2d382f27a9d2c8784ce5936a513bc12c74a@sha256:986d3bd71403f5b684476ecc4844d8d67de4613414e63bbd3e617f18a90293e2
          name: container-image
